package com.ds.transfer.scan.mapper;

import com.ds.transfer.scan.entity.TransferAlarmEntity;
import com.ds.transfer.scan.entity.TransferAlarmEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferAlarmEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int countByExample(TransferAlarmEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int deleteByExample(TransferAlarmEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int insert(TransferAlarmEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int insertSelective(TransferAlarmEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    List<TransferAlarmEntity> selectByExample(TransferAlarmEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    TransferAlarmEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") TransferAlarmEntity record, @Param("example") TransferAlarmEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int updateByExample(@Param("record") TransferAlarmEntity record, @Param("example") TransferAlarmEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int updateByPrimaryKeySelective(TransferAlarmEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_alarm
     *
     * @mbggenerated Thu Dec 10 14:36:28 CST 2015
     */
    int updateByPrimaryKey(TransferAlarmEntity record);
}