package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.AgApiUserEntity;
import com.ds.transfer.record.entity.AgApiUserEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgApiUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int countByExample(AgApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int deleteByExample(AgApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int insert(AgApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int insertSelective(AgApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    List<AgApiUserEntity> selectByExample(AgApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    AgApiUserEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") AgApiUserEntity record, @Param("example") AgApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int updateByExample(@Param("record") AgApiUserEntity record, @Param("example") AgApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int updateByPrimaryKeySelective(AgApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_api_user
     *
     * @mbggenerated Sat Oct 31 16:33:24 CST 2015
     */
    int updateByPrimaryKey(AgApiUserEntity record);
}