package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.ApiInfoEntity;
import com.ds.transfer.record.entity.ApiInfoEntityExample;
import com.ds.transfer.record.entity.ApiInfoEntityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int countByExample(ApiInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int deleteByExample(ApiInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int deleteByPrimaryKey(ApiInfoEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int insert(ApiInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int insertSelective(ApiInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    List<ApiInfoEntity> selectByExample(ApiInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    ApiInfoEntity selectByPrimaryKey(ApiInfoEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") ApiInfoEntity record, @Param("example") ApiInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int updateByExample(@Param("record") ApiInfoEntity record, @Param("example") ApiInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int updateByPrimaryKeySelective(ApiInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    int updateByPrimaryKey(ApiInfoEntity record);
    
    
    List<ApiInfoEntity> selectByExampleWithBLOBs(ApiInfoEntityExample example);
}