package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.BetLimit;
import com.ds.transfer.record.entity.BetLimitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BetLimitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int countByExample(BetLimitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int deleteByExample(BetLimitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int insert(BetLimit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int insertSelective(BetLimit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	List<BetLimit> selectByExample(BetLimitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	BetLimit selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int updateByExampleSelective(@Param("record") BetLimit record,
			@Param("example") BetLimitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int updateByExample(@Param("record") BetLimit record,
			@Param("example") BetLimitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int updateByPrimaryKeySelective(BetLimit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bet_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	int updateByPrimaryKey(BetLimit record);
}