package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.KyApiUserEntity;
import com.ds.transfer.record.entity.KyApiUserEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KyApiUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int countByExample(KyApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int deleteByExample(KyApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int insert(KyApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int insertSelective(KyApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    List<KyApiUserEntity> selectByExample(KyApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    KyApiUserEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") KyApiUserEntity record, @Param("example") KyApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int updateByExample(@Param("record") KyApiUserEntity record, @Param("example") KyApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int updateByPrimaryKeySelective(KyApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_api_user
     *
     * @mbggenerated Sat Apr 28 19:21:37 CST 2018
     */
    int updateByPrimaryKey(KyApiUserEntity record);
}