package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.PtApiUserEntity;
import com.ds.transfer.record.entity.PtApiUserEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtApiUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int countByExample(PtApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int deleteByExample(PtApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int insert(PtApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int insertSelective(PtApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    List<PtApiUserEntity> selectByExample(PtApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    PtApiUserEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") PtApiUserEntity record, @Param("example") PtApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int updateByExample(@Param("record") PtApiUserEntity record, @Param("example") PtApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int updateByPrimaryKeySelective(PtApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_api_user
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    int updateByPrimaryKey(PtApiUserEntity record);
}