package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.SgsApiUserEntity;
import com.ds.transfer.record.entity.SgsApiUserEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SgsApiUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int countByExample(SgsApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int deleteByExample(SgsApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int insert(SgsApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int insertSelective(SgsApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    List<SgsApiUserEntity> selectByExample(SgsApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    SgsApiUserEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") SgsApiUserEntity record, @Param("example") SgsApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int updateByExample(@Param("record") SgsApiUserEntity record, @Param("example") SgsApiUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int updateByPrimaryKeySelective(SgsApiUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgs_api_user
     *
     * @mbggenerated Wed Jun 06 15:43:17 CST 2018
     */
    int updateByPrimaryKey(SgsApiUserEntity record);
}