package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.TransferRecordEntity;
import com.ds.transfer.record.entity.TransferRecordEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int countByExample(TransferRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int deleteByExample(TransferRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int insert(TransferRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int insertSelective(TransferRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    List<TransferRecordEntity> selectByExample(TransferRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    TransferRecordEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") TransferRecordEntity record, @Param("example") TransferRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int updateByExample(@Param("record") TransferRecordEntity record, @Param("example") TransferRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int updateByPrimaryKeySelective(TransferRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbggenerated Tue Dec 29 20:28:58 CST 2015
     */
    int updateByPrimaryKey(TransferRecordEntity record);

	List<TransferRecordEntity> scanTransferError();
	
	List<TransferRecordEntity> selectTransferDetailListInfo(@Param("transRecordId") Long transRecordId);

}