package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.TransferRemarkConfEntity;
import com.ds.transfer.record.entity.TransferRemarkConfEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferRemarkConfEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int countByExample(TransferRemarkConfEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int deleteByExample(TransferRemarkConfEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int insert(TransferRemarkConfEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int insertSelective(TransferRemarkConfEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    List<TransferRemarkConfEntity> selectByExample(TransferRemarkConfEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    TransferRemarkConfEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") TransferRemarkConfEntity record, @Param("example") TransferRemarkConfEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int updateByExample(@Param("record") TransferRemarkConfEntity record, @Param("example") TransferRemarkConfEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int updateByPrimaryKeySelective(TransferRemarkConfEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_remark_conf
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    int updateByPrimaryKey(TransferRemarkConfEntity record);
}