package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.TransferOtherRule;
import com.ds.transfer.record.entity.TransferOtherRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferOtherRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int countByExample(TransferOtherRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int deleteByExample(TransferOtherRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int insert(TransferOtherRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int insertSelective(TransferOtherRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    List<TransferOtherRule> selectByExample(TransferOtherRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    TransferOtherRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") TransferOtherRule record, @Param("example") TransferOtherRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int updateByExample(@Param("record") TransferOtherRule record, @Param("example") TransferOtherRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int updateByPrimaryKeySelective(TransferOtherRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_other_rule
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    int updateByPrimaryKey(TransferOtherRule record);
}