package com.ds.transfer.scan.entity;

import java.util.Date;

public class TransferAlarmEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_alarm.id
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_alarm.billno
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	private String billno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_alarm.status
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_alarm.version
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_alarm.create_time
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_alarm.update_time
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_alarm.remark
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_alarm.id
	 * @return  the value of transfer_alarm.id
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_alarm.id
	 * @param id  the value for transfer_alarm.id
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_alarm.billno
	 * @return  the value of transfer_alarm.billno
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public String getBillno() {
		return billno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_alarm.billno
	 * @param billno  the value for transfer_alarm.billno
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public void setBillno(String billno) {
		this.billno = billno == null ? null : billno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_alarm.status
	 * @return  the value of transfer_alarm.status
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_alarm.status
	 * @param status  the value for transfer_alarm.status
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_alarm.version
	 * @return  the value of transfer_alarm.version
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_alarm.version
	 * @param version  the value for transfer_alarm.version
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_alarm.create_time
	 * @return  the value of transfer_alarm.create_time
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_alarm.create_time
	 * @param createTime  the value for transfer_alarm.create_time
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_alarm.update_time
	 * @return  the value of transfer_alarm.update_time
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_alarm.update_time
	 * @param updateTime  the value for transfer_alarm.update_time
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_alarm.remark
	 * @return  the value of transfer_alarm.remark
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_alarm.remark
	 * @param remark  the value for transfer_alarm.remark
	 * @mbggenerated  Thu Dec 10 14:36:28 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}