package com.ds.transfer.scan.entity;

public class TransferRecordDetailEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.username
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.operator
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.password
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.credit
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.billno
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.status
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.type
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.transfer_before_money
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String transferBeforeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.transfer_after_money
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String transferAfterMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.site_id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.live_id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String liveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.version
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.remark
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.create_time
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record_detail.update_time
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.id
     *
     * @return the value of transfer_record_detail.id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.id
     *
     * @param id the value for transfer_record_detail.id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.username
     *
     * @return the value of transfer_record_detail.username
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.username
     *
     * @param username the value for transfer_record_detail.username
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.operator
     *
     * @return the value of transfer_record_detail.operator
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.operator
     *
     * @param operator the value for transfer_record_detail.operator
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.password
     *
     * @return the value of transfer_record_detail.password
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.password
     *
     * @param password the value for transfer_record_detail.password
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.credit
     *
     * @return the value of transfer_record_detail.credit
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.credit
     *
     * @param credit the value for transfer_record_detail.credit
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.billno
     *
     * @return the value of transfer_record_detail.billno
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.billno
     *
     * @param billno the value for transfer_record_detail.billno
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.status
     *
     * @return the value of transfer_record_detail.status
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.status
     *
     * @param status the value for transfer_record_detail.status
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.type
     *
     * @return the value of transfer_record_detail.type
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.type
     *
     * @param type the value for transfer_record_detail.type
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.transfer_before_money
     *
     * @return the value of transfer_record_detail.transfer_before_money
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getTransferBeforeMoney() {
        return transferBeforeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.transfer_before_money
     *
     * @param transferBeforeMoney the value for transfer_record_detail.transfer_before_money
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setTransferBeforeMoney(String transferBeforeMoney) {
        this.transferBeforeMoney = transferBeforeMoney == null ? null : transferBeforeMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.transfer_after_money
     *
     * @return the value of transfer_record_detail.transfer_after_money
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getTransferAfterMoney() {
        return transferAfterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.transfer_after_money
     *
     * @param transferAfterMoney the value for transfer_record_detail.transfer_after_money
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setTransferAfterMoney(String transferAfterMoney) {
        this.transferAfterMoney = transferAfterMoney == null ? null : transferAfterMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.site_id
     *
     * @return the value of transfer_record_detail.site_id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.site_id
     *
     * @param siteId the value for transfer_record_detail.site_id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.live_id
     *
     * @return the value of transfer_record_detail.live_id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getLiveId() {
        return liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.live_id
     *
     * @param liveId the value for transfer_record_detail.live_id
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setLiveId(String liveId) {
        this.liveId = liveId == null ? null : liveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.version
     *
     * @return the value of transfer_record_detail.version
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.version
     *
     * @param version the value for transfer_record_detail.version
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.remark
     *
     * @return the value of transfer_record_detail.remark
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.remark
     *
     * @param remark the value for transfer_record_detail.remark
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.create_time
     *
     * @return the value of transfer_record_detail.create_time
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.create_time
     *
     * @param createTime the value for transfer_record_detail.create_time
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record_detail.update_time
     *
     * @return the value of transfer_record_detail.update_time
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record_detail.update_time
     *
     * @param updateTime the value for transfer_record_detail.update_time
     *
     * @mbggenerated Fri Dec 04 21:00:30 CST 2015
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}