package com.ds.transfer.http.mapper;

import com.ds.transfer.http.entity.DsIpList;
import com.ds.transfer.http.entity.DsIpListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsIpListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int countByExample(DsIpListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int deleteByExample(DsIpListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int insert(DsIpList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int insertSelective(DsIpList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    List<DsIpList> selectByExample(DsIpListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    DsIpList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") DsIpList record, @Param("example") DsIpListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int updateByExample(@Param("record") DsIpList record, @Param("example") DsIpListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int updateByPrimaryKeySelective(DsIpList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Wed May 23 13:37:20 CST 2018
     */
    int updateByPrimaryKey(DsIpList record);
}