package com.ds.transfer.http.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ds.transfer.http.entity.PlatformUrl;
import com.ds.transfer.http.entity.PlatformUrlExample;

public interface PlatformUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int countByExample(PlatformUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int deleteByExample(PlatformUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int insert(PlatformUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int insertSelective(PlatformUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    List<PlatformUrl> selectByExample(PlatformUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    PlatformUrl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") PlatformUrl record, @Param("example") PlatformUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int updateByExample(@Param("record") PlatformUrl record, @Param("example") PlatformUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int updateByPrimaryKeySelective(PlatformUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_url
     *
     * @mbggenerated Mon Sep 19 15:02:09 CST 2016
     */
    int updateByPrimaryKey(PlatformUrl record);
}