package com.ds.transfer.record.entity;

import java.util.ArrayList;
import java.util.List;

public class ApiInfoEntityExample implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2752252151217794974L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public ApiInfoEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectAgentIsNull() {
            addCriterion("project_agent is null");
            return (Criteria) this;
        }

        public Criteria andProjectAgentIsNotNull() {
            addCriterion("project_agent is not null");
            return (Criteria) this;
        }

        public Criteria andProjectAgentEqualTo(String value) {
            addCriterion("project_agent =", value, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentNotEqualTo(String value) {
            addCriterion("project_agent <>", value, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentGreaterThan(String value) {
            addCriterion("project_agent >", value, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentGreaterThanOrEqualTo(String value) {
            addCriterion("project_agent >=", value, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentLessThan(String value) {
            addCriterion("project_agent <", value, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentLessThanOrEqualTo(String value) {
            addCriterion("project_agent <=", value, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentLike(String value) {
            addCriterion("project_agent like", value, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentNotLike(String value) {
            addCriterion("project_agent not like", value, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentIn(List<String> values) {
            addCriterion("project_agent in", values, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentNotIn(List<String> values) {
            addCriterion("project_agent not in", values, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentBetween(String value1, String value2) {
            addCriterion("project_agent between", value1, value2, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andProjectAgentNotBetween(String value1, String value2) {
            addCriterion("project_agent not between", value1, value2, "projectAgent");
            return (Criteria) this;
        }

        public Criteria andPrefixIsNull() {
            addCriterion("prefix is null");
            return (Criteria) this;
        }

        public Criteria andPrefixIsNotNull() {
            addCriterion("prefix is not null");
            return (Criteria) this;
        }

        public Criteria andPrefixEqualTo(String value) {
            addCriterion("prefix =", value, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixNotEqualTo(String value) {
            addCriterion("prefix <>", value, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixGreaterThan(String value) {
            addCriterion("prefix >", value, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixGreaterThanOrEqualTo(String value) {
            addCriterion("prefix >=", value, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixLessThan(String value) {
            addCriterion("prefix <", value, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixLessThanOrEqualTo(String value) {
            addCriterion("prefix <=", value, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixLike(String value) {
            addCriterion("prefix like", value, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixNotLike(String value) {
            addCriterion("prefix not like", value, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixIn(List<String> values) {
            addCriterion("prefix in", values, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixNotIn(List<String> values) {
            addCriterion("prefix not in", values, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixBetween(String value1, String value2) {
            addCriterion("prefix between", value1, value2, "prefix");
            return (Criteria) this;
        }

        public Criteria andPrefixNotBetween(String value1, String value2) {
            addCriterion("prefix not between", value1, value2, "prefix");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNull() {
            addCriterion("site_id is null");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNotNull() {
            addCriterion("site_id is not null");
            return (Criteria) this;
        }

        public Criteria andSiteIdEqualTo(Integer value) {
            addCriterion("site_id =", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotEqualTo(Integer value) {
            addCriterion("site_id <>", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThan(Integer value) {
            addCriterion("site_id >", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("site_id >=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThan(Integer value) {
            addCriterion("site_id <", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThanOrEqualTo(Integer value) {
            addCriterion("site_id <=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIn(List<Integer> values) {
            addCriterion("site_id in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotIn(List<Integer> values) {
            addCriterion("site_id not in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdBetween(Integer value1, Integer value2) {
            addCriterion("site_id between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("site_id not between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andAgentIsNull() {
            addCriterion("agent is null");
            return (Criteria) this;
        }

        public Criteria andAgentIsNotNull() {
            addCriterion("agent is not null");
            return (Criteria) this;
        }

        public Criteria andAgentEqualTo(String value) {
            addCriterion("agent =", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotEqualTo(String value) {
            addCriterion("agent <>", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThan(String value) {
            addCriterion("agent >", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThanOrEqualTo(String value) {
            addCriterion("agent >=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThan(String value) {
            addCriterion("agent <", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThanOrEqualTo(String value) {
            addCriterion("agent <=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLike(String value) {
            addCriterion("agent like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotLike(String value) {
            addCriterion("agent not like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentIn(List<String> values) {
            addCriterion("agent in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotIn(List<String> values) {
            addCriterion("agent not in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentBetween(String value1, String value2) {
            addCriterion("agent between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotBetween(String value1, String value2) {
            addCriterion("agent not between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andWebUrlIsNull() {
            addCriterion("web_url is null");
            return (Criteria) this;
        }

        public Criteria andWebUrlIsNotNull() {
            addCriterion("web_url is not null");
            return (Criteria) this;
        }

        public Criteria andWebUrlEqualTo(String value) {
            addCriterion("web_url =", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotEqualTo(String value) {
            addCriterion("web_url <>", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlGreaterThan(String value) {
            addCriterion("web_url >", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlGreaterThanOrEqualTo(String value) {
            addCriterion("web_url >=", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLessThan(String value) {
            addCriterion("web_url <", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLessThanOrEqualTo(String value) {
            addCriterion("web_url <=", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLike(String value) {
            addCriterion("web_url like", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotLike(String value) {
            addCriterion("web_url not like", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlIn(List<String> values) {
            addCriterion("web_url in", values, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotIn(List<String> values) {
            addCriterion("web_url not in", values, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlBetween(String value1, String value2) {
            addCriterion("web_url between", value1, value2, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotBetween(String value1, String value2) {
            addCriterion("web_url not between", value1, value2, "webUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlIsNull() {
            addCriterion("report_url is null");
            return (Criteria) this;
        }

        public Criteria andReportUrlIsNotNull() {
            addCriterion("report_url is not null");
            return (Criteria) this;
        }

        public Criteria andReportUrlEqualTo(String value) {
            addCriterion("report_url =", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlNotEqualTo(String value) {
            addCriterion("report_url <>", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlGreaterThan(String value) {
            addCriterion("report_url >", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlGreaterThanOrEqualTo(String value) {
            addCriterion("report_url >=", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlLessThan(String value) {
            addCriterion("report_url <", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlLessThanOrEqualTo(String value) {
            addCriterion("report_url <=", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlLike(String value) {
            addCriterion("report_url like", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlNotLike(String value) {
            addCriterion("report_url not like", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlIn(List<String> values) {
            addCriterion("report_url in", values, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlNotIn(List<String> values) {
            addCriterion("report_url not in", values, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlBetween(String value1, String value2) {
            addCriterion("report_url between", value1, value2, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlNotBetween(String value1, String value2) {
            addCriterion("report_url not between", value1, value2, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andHashcodeIsNull() {
            addCriterion("hashCode is null");
            return (Criteria) this;
        }

        public Criteria andHashcodeIsNotNull() {
            addCriterion("hashCode is not null");
            return (Criteria) this;
        }

        public Criteria andHashcodeEqualTo(String value) {
            addCriterion("hashCode =", value, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeNotEqualTo(String value) {
            addCriterion("hashCode <>", value, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeGreaterThan(String value) {
            addCriterion("hashCode >", value, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeGreaterThanOrEqualTo(String value) {
            addCriterion("hashCode >=", value, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeLessThan(String value) {
            addCriterion("hashCode <", value, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeLessThanOrEqualTo(String value) {
            addCriterion("hashCode <=", value, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeLike(String value) {
            addCriterion("hashCode like", value, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeNotLike(String value) {
            addCriterion("hashCode not like", value, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeIn(List<String> values) {
            addCriterion("hashCode in", values, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeNotIn(List<String> values) {
            addCriterion("hashCode not in", values, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeBetween(String value1, String value2) {
            addCriterion("hashCode between", value1, value2, "hashcode");
            return (Criteria) this;
        }

        public Criteria andHashcodeNotBetween(String value1, String value2) {
            addCriterion("hashCode not between", value1, value2, "hashcode");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andKeybIsNull() {
            addCriterion("keyB is null");
            return (Criteria) this;
        }

        public Criteria andKeybIsNotNull() {
            addCriterion("keyB is not null");
            return (Criteria) this;
        }

        public Criteria andKeybEqualTo(String value) {
            addCriterion("keyB =", value, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybNotEqualTo(String value) {
            addCriterion("keyB <>", value, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybGreaterThan(String value) {
            addCriterion("keyB >", value, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybGreaterThanOrEqualTo(String value) {
            addCriterion("keyB >=", value, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybLessThan(String value) {
            addCriterion("keyB <", value, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybLessThanOrEqualTo(String value) {
            addCriterion("keyB <=", value, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybLike(String value) {
            addCriterion("keyB like", value, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybNotLike(String value) {
            addCriterion("keyB not like", value, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybIn(List<String> values) {
            addCriterion("keyB in", values, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybNotIn(List<String> values) {
            addCriterion("keyB not in", values, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybBetween(String value1, String value2) {
            addCriterion("keyB between", value1, value2, "keyb");
            return (Criteria) this;
        }

        public Criteria andKeybNotBetween(String value1, String value2) {
            addCriterion("keyB not between", value1, value2, "keyb");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIsNull() {
            addCriterion("currency_type is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIsNotNull() {
            addCriterion("currency_type is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeEqualTo(String value) {
            addCriterion("currency_type =", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotEqualTo(String value) {
            addCriterion("currency_type <>", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeGreaterThan(String value) {
            addCriterion("currency_type >", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("currency_type >=", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLessThan(String value) {
            addCriterion("currency_type <", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLessThanOrEqualTo(String value) {
            addCriterion("currency_type <=", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLike(String value) {
            addCriterion("currency_type like", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotLike(String value) {
            addCriterion("currency_type not like", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIn(List<String> values) {
            addCriterion("currency_type in", values, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotIn(List<String> values) {
            addCriterion("currency_type not in", values, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeBetween(String value1, String value2) {
            addCriterion("currency_type between", value1, value2, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotBetween(String value1, String value2) {
            addCriterion("currency_type not between", value1, value2, "currencyType");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("language like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("language not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlIsNull() {
            addCriterion("center_money_url is null");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlIsNotNull() {
            addCriterion("center_money_url is not null");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlEqualTo(String value) {
            addCriterion("center_money_url =", value, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlNotEqualTo(String value) {
            addCriterion("center_money_url <>", value, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlGreaterThan(String value) {
            addCriterion("center_money_url >", value, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlGreaterThanOrEqualTo(String value) {
            addCriterion("center_money_url >=", value, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlLessThan(String value) {
            addCriterion("center_money_url <", value, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlLessThanOrEqualTo(String value) {
            addCriterion("center_money_url <=", value, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlLike(String value) {
            addCriterion("center_money_url like", value, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlNotLike(String value) {
            addCriterion("center_money_url not like", value, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlIn(List<String> values) {
            addCriterion("center_money_url in", values, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlNotIn(List<String> values) {
            addCriterion("center_money_url not in", values, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlBetween(String value1, String value2) {
            addCriterion("center_money_url between", value1, value2, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyUrlNotBetween(String value1, String value2) {
            addCriterion("center_money_url not between", value1, value2, "centerMoneyUrl");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyIsNull() {
            addCriterion("center_money_fromKey is null");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyIsNotNull() {
            addCriterion("center_money_fromKey is not null");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyEqualTo(String value) {
            addCriterion("center_money_fromKey =", value, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyNotEqualTo(String value) {
            addCriterion("center_money_fromKey <>", value, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyGreaterThan(String value) {
            addCriterion("center_money_fromKey >", value, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyGreaterThanOrEqualTo(String value) {
            addCriterion("center_money_fromKey >=", value, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyLessThan(String value) {
            addCriterion("center_money_fromKey <", value, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyLessThanOrEqualTo(String value) {
            addCriterion("center_money_fromKey <=", value, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyLike(String value) {
            addCriterion("center_money_fromKey like", value, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyNotLike(String value) {
            addCriterion("center_money_fromKey not like", value, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyIn(List<String> values) {
            addCriterion("center_money_fromKey in", values, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyNotIn(List<String> values) {
            addCriterion("center_money_fromKey not in", values, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyBetween(String value1, String value2) {
            addCriterion("center_money_fromKey between", value1, value2, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andCenterMoneyFromkeyNotBetween(String value1, String value2) {
            addCriterion("center_money_fromKey not between", value1, value2, "centerMoneyFromkey");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlIsNull() {
            addCriterion("ag_request_url is null");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlIsNotNull() {
            addCriterion("ag_request_url is not null");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlEqualTo(String value) {
            addCriterion("ag_request_url =", value, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlNotEqualTo(String value) {
            addCriterion("ag_request_url <>", value, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlGreaterThan(String value) {
            addCriterion("ag_request_url >", value, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ag_request_url >=", value, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlLessThan(String value) {
            addCriterion("ag_request_url <", value, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlLessThanOrEqualTo(String value) {
            addCriterion("ag_request_url <=", value, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlLike(String value) {
            addCriterion("ag_request_url like", value, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlNotLike(String value) {
            addCriterion("ag_request_url not like", value, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlIn(List<String> values) {
            addCriterion("ag_request_url in", values, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlNotIn(List<String> values) {
            addCriterion("ag_request_url not in", values, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlBetween(String value1, String value2) {
            addCriterion("ag_request_url between", value1, value2, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgRequestUrlNotBetween(String value1, String value2) {
            addCriterion("ag_request_url not between", value1, value2, "agRequestUrl");
            return (Criteria) this;
        }

        public Criteria andAgProxyIsNull() {
            addCriterion("ag_proxy is null");
            return (Criteria) this;
        }

        public Criteria andAgProxyIsNotNull() {
            addCriterion("ag_proxy is not null");
            return (Criteria) this;
        }

        public Criteria andAgProxyEqualTo(String value) {
            addCriterion("ag_proxy =", value, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyNotEqualTo(String value) {
            addCriterion("ag_proxy <>", value, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyGreaterThan(String value) {
            addCriterion("ag_proxy >", value, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyGreaterThanOrEqualTo(String value) {
            addCriterion("ag_proxy >=", value, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyLessThan(String value) {
            addCriterion("ag_proxy <", value, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyLessThanOrEqualTo(String value) {
            addCriterion("ag_proxy <=", value, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyLike(String value) {
            addCriterion("ag_proxy like", value, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyNotLike(String value) {
            addCriterion("ag_proxy not like", value, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyIn(List<String> values) {
            addCriterion("ag_proxy in", values, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyNotIn(List<String> values) {
            addCriterion("ag_proxy not in", values, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyBetween(String value1, String value2) {
            addCriterion("ag_proxy between", value1, value2, "agProxy");
            return (Criteria) this;
        }

        public Criteria andAgProxyNotBetween(String value1, String value2) {
            addCriterion("ag_proxy not between", value1, value2, "agProxy");
            return (Criteria) this;
        }

        public Criteria andSecretIsNull() {
            addCriterion("secret is null");
            return (Criteria) this;
        }

        public Criteria andSecretIsNotNull() {
            addCriterion("secret is not null");
            return (Criteria) this;
        }

        public Criteria andSecretEqualTo(String value) {
            addCriterion("secret =", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotEqualTo(String value) {
            addCriterion("secret <>", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretGreaterThan(String value) {
            addCriterion("secret >", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretGreaterThanOrEqualTo(String value) {
            addCriterion("secret >=", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLessThan(String value) {
            addCriterion("secret <", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLessThanOrEqualTo(String value) {
            addCriterion("secret <=", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLike(String value) {
            addCriterion("secret like", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotLike(String value) {
            addCriterion("secret not like", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretIn(List<String> values) {
            addCriterion("secret in", values, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotIn(List<String> values) {
            addCriterion("secret not in", values, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretBetween(String value1, String value2) {
            addCriterion("secret between", value1, value2, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotBetween(String value1, String value2) {
            addCriterion("secret not between", value1, value2, "secret");
            return (Criteria) this;
        }

        public Criteria andBbinAgentIsNull() {
            addCriterion("bbin_agent is null");
            return (Criteria) this;
        }

        public Criteria andBbinAgentIsNotNull() {
            addCriterion("bbin_agent is not null");
            return (Criteria) this;
        }

        public Criteria andBbinAgentEqualTo(String value) {
            addCriterion("bbin_agent =", value, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentNotEqualTo(String value) {
            addCriterion("bbin_agent <>", value, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentGreaterThan(String value) {
            addCriterion("bbin_agent >", value, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentGreaterThanOrEqualTo(String value) {
            addCriterion("bbin_agent >=", value, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentLessThan(String value) {
            addCriterion("bbin_agent <", value, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentLessThanOrEqualTo(String value) {
            addCriterion("bbin_agent <=", value, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentLike(String value) {
            addCriterion("bbin_agent like", value, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentNotLike(String value) {
            addCriterion("bbin_agent not like", value, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentIn(List<String> values) {
            addCriterion("bbin_agent in", values, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentNotIn(List<String> values) {
            addCriterion("bbin_agent not in", values, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentBetween(String value1, String value2) {
            addCriterion("bbin_agent between", value1, value2, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andBbinAgentNotBetween(String value1, String value2) {
            addCriterion("bbin_agent not between", value1, value2, "bbinAgent");
            return (Criteria) this;
        }

        public Criteria andH8AgentIsNull() {
            addCriterion("h8_agent is null");
            return (Criteria) this;
        }

        public Criteria andH8AgentIsNotNull() {
            addCriterion("h8_agent is not null");
            return (Criteria) this;
        }

        public Criteria andH8AgentEqualTo(String value) {
            addCriterion("h8_agent =", value, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentNotEqualTo(String value) {
            addCriterion("h8_agent <>", value, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentGreaterThan(String value) {
            addCriterion("h8_agent >", value, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentGreaterThanOrEqualTo(String value) {
            addCriterion("h8_agent >=", value, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentLessThan(String value) {
            addCriterion("h8_agent <", value, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentLessThanOrEqualTo(String value) {
            addCriterion("h8_agent <=", value, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentLike(String value) {
            addCriterion("h8_agent like", value, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentNotLike(String value) {
            addCriterion("h8_agent not like", value, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentIn(List<String> values) {
            addCriterion("h8_agent in", values, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentNotIn(List<String> values) {
            addCriterion("h8_agent not in", values, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentBetween(String value1, String value2) {
            addCriterion("h8_agent between", value1, value2, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8AgentNotBetween(String value1, String value2) {
            addCriterion("h8_agent not between", value1, value2, "h8Agent");
            return (Criteria) this;
        }

        public Criteria andH8HostIsNull() {
            addCriterion("h8_host is null");
            return (Criteria) this;
        }

        public Criteria andH8HostIsNotNull() {
            addCriterion("h8_host is not null");
            return (Criteria) this;
        }

        public Criteria andH8HostEqualTo(String value) {
            addCriterion("h8_host =", value, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostNotEqualTo(String value) {
            addCriterion("h8_host <>", value, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostGreaterThan(String value) {
            addCriterion("h8_host >", value, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostGreaterThanOrEqualTo(String value) {
            addCriterion("h8_host >=", value, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostLessThan(String value) {
            addCriterion("h8_host <", value, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostLessThanOrEqualTo(String value) {
            addCriterion("h8_host <=", value, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostLike(String value) {
            addCriterion("h8_host like", value, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostNotLike(String value) {
            addCriterion("h8_host not like", value, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostIn(List<String> values) {
            addCriterion("h8_host in", values, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostNotIn(List<String> values) {
            addCriterion("h8_host not in", values, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostBetween(String value1, String value2) {
            addCriterion("h8_host between", value1, value2, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8HostNotBetween(String value1, String value2) {
            addCriterion("h8_host not between", value1, value2, "h8Host");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlIsNull() {
            addCriterion("h8_request_url is null");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlIsNotNull() {
            addCriterion("h8_request_url is not null");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlEqualTo(String value) {
            addCriterion("h8_request_url =", value, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlNotEqualTo(String value) {
            addCriterion("h8_request_url <>", value, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlGreaterThan(String value) {
            addCriterion("h8_request_url >", value, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlGreaterThanOrEqualTo(String value) {
            addCriterion("h8_request_url >=", value, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlLessThan(String value) {
            addCriterion("h8_request_url <", value, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlLessThanOrEqualTo(String value) {
            addCriterion("h8_request_url <=", value, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlLike(String value) {
            addCriterion("h8_request_url like", value, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlNotLike(String value) {
            addCriterion("h8_request_url not like", value, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlIn(List<String> values) {
            addCriterion("h8_request_url in", values, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlNotIn(List<String> values) {
            addCriterion("h8_request_url not in", values, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlBetween(String value1, String value2) {
            addCriterion("h8_request_url between", value1, value2, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andH8RequestUrlNotBetween(String value1, String value2) {
            addCriterion("h8_request_url not between", value1, value2, "h8RequestUrl");
            return (Criteria) this;
        }

        public Criteria andLiveIdIsNull() {
            addCriterion("live_id is null");
            return (Criteria) this;
        }

        public Criteria andLiveIdIsNotNull() {
            addCriterion("live_id is not null");
            return (Criteria) this;
        }

        public Criteria andLiveIdEqualTo(Integer value) {
            addCriterion("live_id =", value, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdNotEqualTo(Integer value) {
            addCriterion("live_id <>", value, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdGreaterThan(Integer value) {
            addCriterion("live_id >", value, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("live_id >=", value, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdLessThan(Integer value) {
            addCriterion("live_id <", value, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdLessThanOrEqualTo(Integer value) {
            addCriterion("live_id <=", value, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdIn(List<Integer> values) {
            addCriterion("live_id in", values, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdNotIn(List<Integer> values) {
            addCriterion("live_id not in", values, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdBetween(Integer value1, Integer value2) {
            addCriterion("live_id between", value1, value2, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveIdNotBetween(Integer value1, Integer value2) {
            addCriterion("live_id not between", value1, value2, "liveId");
            return (Criteria) this;
        }

        public Criteria andLiveNameIsNull() {
            addCriterion("live_name is null");
            return (Criteria) this;
        }

        public Criteria andLiveNameIsNotNull() {
            addCriterion("live_name is not null");
            return (Criteria) this;
        }

        public Criteria andLiveNameEqualTo(String value) {
            addCriterion("live_name =", value, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameNotEqualTo(String value) {
            addCriterion("live_name <>", value, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameGreaterThan(String value) {
            addCriterion("live_name >", value, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameGreaterThanOrEqualTo(String value) {
            addCriterion("live_name >=", value, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameLessThan(String value) {
            addCriterion("live_name <", value, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameLessThanOrEqualTo(String value) {
            addCriterion("live_name <=", value, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameLike(String value) {
            addCriterion("live_name like", value, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameNotLike(String value) {
            addCriterion("live_name not like", value, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameIn(List<String> values) {
            addCriterion("live_name in", values, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameNotIn(List<String> values) {
            addCriterion("live_name not in", values, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameBetween(String value1, String value2) {
            addCriterion("live_name between", value1, value2, "liveName");
            return (Criteria) this;
        }

        public Criteria andLiveNameNotBetween(String value1, String value2) {
            addCriterion("live_name not between", value1, value2, "liveName");
            return (Criteria) this;
        }

        public Criteria andIsDemoIsNull() {
            addCriterion("is_demo is null");
            return (Criteria) this;
        }

        public Criteria andIsDemoIsNotNull() {
            addCriterion("is_demo is not null");
            return (Criteria) this;
        }

        public Criteria andIsDemoEqualTo(Integer value) {
            addCriterion("is_demo =", value, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoNotEqualTo(Integer value) {
            addCriterion("is_demo <>", value, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoGreaterThan(Integer value) {
            addCriterion("is_demo >", value, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_demo >=", value, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoLessThan(Integer value) {
            addCriterion("is_demo <", value, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoLessThanOrEqualTo(Integer value) {
            addCriterion("is_demo <=", value, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoIn(List<Integer> values) {
            addCriterion("is_demo in", values, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoNotIn(List<Integer> values) {
            addCriterion("is_demo not in", values, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoBetween(Integer value1, Integer value2) {
            addCriterion("is_demo between", value1, value2, "isDemo");
            return (Criteria) this;
        }

        public Criteria andIsDemoNotBetween(Integer value1, Integer value2) {
            addCriterion("is_demo not between", value1, value2, "isDemo");
            return (Criteria) this;
        }

        public Criteria andLiveStatusIsNull() {
            addCriterion("live_status is null");
            return (Criteria) this;
        }

        public Criteria andLiveStatusIsNotNull() {
            addCriterion("live_status is not null");
            return (Criteria) this;
        }

        public Criteria andLiveStatusEqualTo(Integer value) {
            addCriterion("live_status =", value, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusNotEqualTo(Integer value) {
            addCriterion("live_status <>", value, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusGreaterThan(Integer value) {
            addCriterion("live_status >", value, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("live_status >=", value, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusLessThan(Integer value) {
            addCriterion("live_status <", value, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusLessThanOrEqualTo(Integer value) {
            addCriterion("live_status <=", value, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusIn(List<Integer> values) {
            addCriterion("live_status in", values, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusNotIn(List<Integer> values) {
            addCriterion("live_status not in", values, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusBetween(Integer value1, Integer value2) {
            addCriterion("live_status between", value1, value2, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andLiveStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("live_status not between", value1, value2, "liveStatus");
            return (Criteria) this;
        }

        public Criteria andBbinUrlIsNull() {
            addCriterion("bbin_url is null");
            return (Criteria) this;
        }

        public Criteria andBbinUrlIsNotNull() {
            addCriterion("bbin_url is not null");
            return (Criteria) this;
        }

        public Criteria andBbinUrlEqualTo(String value) {
            addCriterion("bbin_url =", value, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlNotEqualTo(String value) {
            addCriterion("bbin_url <>", value, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlGreaterThan(String value) {
            addCriterion("bbin_url >", value, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlGreaterThanOrEqualTo(String value) {
            addCriterion("bbin_url >=", value, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlLessThan(String value) {
            addCriterion("bbin_url <", value, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlLessThanOrEqualTo(String value) {
            addCriterion("bbin_url <=", value, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlLike(String value) {
            addCriterion("bbin_url like", value, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlNotLike(String value) {
            addCriterion("bbin_url not like", value, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlIn(List<String> values) {
            addCriterion("bbin_url in", values, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlNotIn(List<String> values) {
            addCriterion("bbin_url not in", values, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlBetween(String value1, String value2) {
            addCriterion("bbin_url between", value1, value2, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andBbinUrlNotBetween(String value1, String value2) {
            addCriterion("bbin_url not between", value1, value2, "bbinUrl");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyIsNull() {
            addCriterion("pt_entity_key is null");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyIsNotNull() {
            addCriterion("pt_entity_key is not null");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyEqualTo(String value) {
            addCriterion("pt_entity_key =", value, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyNotEqualTo(String value) {
            addCriterion("pt_entity_key <>", value, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyGreaterThan(String value) {
            addCriterion("pt_entity_key >", value, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyGreaterThanOrEqualTo(String value) {
            addCriterion("pt_entity_key >=", value, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyLessThan(String value) {
            addCriterion("pt_entity_key <", value, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyLessThanOrEqualTo(String value) {
            addCriterion("pt_entity_key <=", value, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyLike(String value) {
            addCriterion("pt_entity_key like", value, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyNotLike(String value) {
            addCriterion("pt_entity_key not like", value, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyIn(List<String> values) {
            addCriterion("pt_entity_key in", values, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyNotIn(List<String> values) {
            addCriterion("pt_entity_key not in", values, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyBetween(String value1, String value2) {
            addCriterion("pt_entity_key between", value1, value2, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andPtEntityKeyNotBetween(String value1, String value2) {
            addCriterion("pt_entity_key not between", value1, value2, "ptEntityKey");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeIsNull() {
            addCriterion("ag_odd_type is null");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeIsNotNull() {
            addCriterion("ag_odd_type is not null");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeEqualTo(String value) {
            addCriterion("ag_odd_type =", value, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeNotEqualTo(String value) {
            addCriterion("ag_odd_type <>", value, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeGreaterThan(String value) {
            addCriterion("ag_odd_type >", value, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ag_odd_type >=", value, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeLessThan(String value) {
            addCriterion("ag_odd_type <", value, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeLessThanOrEqualTo(String value) {
            addCriterion("ag_odd_type <=", value, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeLike(String value) {
            addCriterion("ag_odd_type like", value, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeNotLike(String value) {
            addCriterion("ag_odd_type not like", value, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeIn(List<String> values) {
            addCriterion("ag_odd_type in", values, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeNotIn(List<String> values) {
            addCriterion("ag_odd_type not in", values, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeBetween(String value1, String value2) {
            addCriterion("ag_odd_type between", value1, value2, "agOddType");
            return (Criteria) this;
        }

        public Criteria andAgOddTypeNotBetween(String value1, String value2) {
            addCriterion("ag_odd_type not between", value1, value2, "agOddType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api_info
     *
     * @mbggenerated do_not_delete_during_merge Mon May 28 14:46:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api_info
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}