package com.ds.transfer.record.entity;

public class ApiInfoEntityKey implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8816233373815200265L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.project_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String projectAgent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.id
     *
     * @return the value of api_info.id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.id
     *
     * @param id the value for api_info.id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.project_agent
     *
     * @return the value of api_info.project_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getProjectAgent() {
        return projectAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.project_agent
     *
     * @param projectAgent the value for api_info.project_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setProjectAgent(String projectAgent) {
        this.projectAgent = projectAgent == null ? null : projectAgent.trim();
    }
}