package com.ds.transfer.record.entity;

public class ApiInfoEntity extends ApiInfoEntityKey implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3381508168696543932L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.prefix
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String prefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.site_id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.password
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.web_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String webUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.report_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String reportUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.hashCode
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String hashcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.remark
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.keyB
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String keyb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.currency_type
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String currencyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.language
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.center_money_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String centerMoneyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.center_money_fromKey
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String centerMoneyFromkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.ag_request_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String agRequestUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.ag_proxy
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String agProxy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.secret
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.bbin_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String bbinAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.h8_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String h8Agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.h8_host
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String h8Host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.h8_request_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String h8RequestUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.live_id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private Integer liveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.live_name
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String liveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.is_demo
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private Integer isDemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.live_status
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private Integer liveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.bbin_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String bbinUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.pt_entity_key
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String ptEntityKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_info.ag_odd_type
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    private String agOddType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.prefix
     *
     * @return the value of api_info.prefix
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.prefix
     *
     * @param prefix the value for api_info.prefix
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.site_id
     *
     * @return the value of api_info.site_id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.site_id
     *
     * @param siteId the value for api_info.site_id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.agent
     *
     * @return the value of api_info.agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.agent
     *
     * @param agent the value for api_info.agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setAgent(String agent) {
        this.agent = agent == null ? null : agent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.password
     *
     * @return the value of api_info.password
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.password
     *
     * @param password the value for api_info.password
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.web_url
     *
     * @return the value of api_info.web_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.web_url
     *
     * @param webUrl the value for api_info.web_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl == null ? null : webUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.report_url
     *
     * @return the value of api_info.report_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getReportUrl() {
        return reportUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.report_url
     *
     * @param reportUrl the value for api_info.report_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setReportUrl(String reportUrl) {
        this.reportUrl = reportUrl == null ? null : reportUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.hashCode
     *
     * @return the value of api_info.hashCode
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getHashcode() {
        return hashcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.hashCode
     *
     * @param hashcode the value for api_info.hashCode
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setHashcode(String hashcode) {
        this.hashcode = hashcode == null ? null : hashcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.remark
     *
     * @return the value of api_info.remark
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.remark
     *
     * @param remark the value for api_info.remark
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.keyB
     *
     * @return the value of api_info.keyB
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getKeyb() {
        return keyb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.keyB
     *
     * @param keyb the value for api_info.keyB
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setKeyb(String keyb) {
        this.keyb = keyb == null ? null : keyb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.currency_type
     *
     * @return the value of api_info.currency_type
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.currency_type
     *
     * @param currencyType the value for api_info.currency_type
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.language
     *
     * @return the value of api_info.language
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.language
     *
     * @param language the value for api_info.language
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.center_money_url
     *
     * @return the value of api_info.center_money_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getCenterMoneyUrl() {
        return centerMoneyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.center_money_url
     *
     * @param centerMoneyUrl the value for api_info.center_money_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setCenterMoneyUrl(String centerMoneyUrl) {
        this.centerMoneyUrl = centerMoneyUrl == null ? null : centerMoneyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.center_money_fromKey
     *
     * @return the value of api_info.center_money_fromKey
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getCenterMoneyFromkey() {
        return centerMoneyFromkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.center_money_fromKey
     *
     * @param centerMoneyFromkey the value for api_info.center_money_fromKey
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setCenterMoneyFromkey(String centerMoneyFromkey) {
        this.centerMoneyFromkey = centerMoneyFromkey == null ? null : centerMoneyFromkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.ag_request_url
     *
     * @return the value of api_info.ag_request_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getAgRequestUrl() {
        return agRequestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.ag_request_url
     *
     * @param agRequestUrl the value for api_info.ag_request_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setAgRequestUrl(String agRequestUrl) {
        this.agRequestUrl = agRequestUrl == null ? null : agRequestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.ag_proxy
     *
     * @return the value of api_info.ag_proxy
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getAgProxy() {
        return agProxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.ag_proxy
     *
     * @param agProxy the value for api_info.ag_proxy
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setAgProxy(String agProxy) {
        this.agProxy = agProxy == null ? null : agProxy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.secret
     *
     * @return the value of api_info.secret
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.secret
     *
     * @param secret the value for api_info.secret
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.bbin_agent
     *
     * @return the value of api_info.bbin_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getBbinAgent() {
        return bbinAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.bbin_agent
     *
     * @param bbinAgent the value for api_info.bbin_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setBbinAgent(String bbinAgent) {
        this.bbinAgent = bbinAgent == null ? null : bbinAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.h8_agent
     *
     * @return the value of api_info.h8_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getH8Agent() {
        return h8Agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.h8_agent
     *
     * @param h8Agent the value for api_info.h8_agent
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setH8Agent(String h8Agent) {
        this.h8Agent = h8Agent == null ? null : h8Agent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.h8_host
     *
     * @return the value of api_info.h8_host
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getH8Host() {
        return h8Host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.h8_host
     *
     * @param h8Host the value for api_info.h8_host
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setH8Host(String h8Host) {
        this.h8Host = h8Host == null ? null : h8Host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.h8_request_url
     *
     * @return the value of api_info.h8_request_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getH8RequestUrl() {
        return h8RequestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.h8_request_url
     *
     * @param h8RequestUrl the value for api_info.h8_request_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setH8RequestUrl(String h8RequestUrl) {
        this.h8RequestUrl = h8RequestUrl == null ? null : h8RequestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.live_id
     *
     * @return the value of api_info.live_id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public Integer getLiveId() {
        return liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.live_id
     *
     * @param liveId the value for api_info.live_id
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setLiveId(Integer liveId) {
        this.liveId = liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.live_name
     *
     * @return the value of api_info.live_name
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getLiveName() {
        return liveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.live_name
     *
     * @param liveName the value for api_info.live_name
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setLiveName(String liveName) {
        this.liveName = liveName == null ? null : liveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.is_demo
     *
     * @return the value of api_info.is_demo
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public Integer getIsDemo() {
        return isDemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.is_demo
     *
     * @param isDemo the value for api_info.is_demo
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setIsDemo(Integer isDemo) {
        this.isDemo = isDemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.live_status
     *
     * @return the value of api_info.live_status
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public Integer getLiveStatus() {
        return liveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.live_status
     *
     * @param liveStatus the value for api_info.live_status
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setLiveStatus(Integer liveStatus) {
        this.liveStatus = liveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.bbin_url
     *
     * @return the value of api_info.bbin_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getBbinUrl() {
        return bbinUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.bbin_url
     *
     * @param bbinUrl the value for api_info.bbin_url
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setBbinUrl(String bbinUrl) {
        this.bbinUrl = bbinUrl == null ? null : bbinUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.pt_entity_key
     *
     * @return the value of api_info.pt_entity_key
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getPtEntityKey() {
        return ptEntityKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.pt_entity_key
     *
     * @param ptEntityKey the value for api_info.pt_entity_key
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setPtEntityKey(String ptEntityKey) {
        this.ptEntityKey = ptEntityKey == null ? null : ptEntityKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_info.ag_odd_type
     *
     * @return the value of api_info.ag_odd_type
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public String getAgOddType() {
        return agOddType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_info.ag_odd_type
     *
     * @param agOddType the value for api_info.ag_odd_type
     *
     * @mbggenerated Mon May 28 14:46:07 CST 2018
     */
    public void setAgOddType(String agOddType) {
        this.agOddType = agOddType == null ? null : agOddType.trim();
    }
}