package com.ds.transfer.record.entity;

public class BetLimit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.live_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String liveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.live_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String liveName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.site_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.site_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String siteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.agent_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String agentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.agent_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String agentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.max_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String maxLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.min_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String minLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.oddtype
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String oddtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.currency_type
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String currencyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.operator
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.state
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.create_time
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bet_limit.update_time
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	private String updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.id
	 * @return  the value of bet_limit.id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.id
	 * @param id  the value for bet_limit.id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.live_id
	 * @return  the value of bet_limit.live_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getLiveId() {
		return liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.live_id
	 * @param liveId  the value for bet_limit.live_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setLiveId(String liveId) {
		this.liveId = liveId == null ? null : liveId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.live_name
	 * @return  the value of bet_limit.live_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getLiveName() {
		return liveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.live_name
	 * @param liveName  the value for bet_limit.live_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setLiveName(String liveName) {
		this.liveName = liveName == null ? null : liveName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.site_id
	 * @return  the value of bet_limit.site_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.site_id
	 * @param siteId  the value for bet_limit.site_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.site_name
	 * @return  the value of bet_limit.site_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.site_name
	 * @param siteName  the value for bet_limit.site_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName == null ? null : siteName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.agent_id
	 * @return  the value of bet_limit.agent_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getAgentId() {
		return agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.agent_id
	 * @param agentId  the value for bet_limit.agent_id
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setAgentId(String agentId) {
		this.agentId = agentId == null ? null : agentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.agent_name
	 * @return  the value of bet_limit.agent_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getAgentName() {
		return agentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.agent_name
	 * @param agentName  the value for bet_limit.agent_name
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setAgentName(String agentName) {
		this.agentName = agentName == null ? null : agentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.max_limit
	 * @return  the value of bet_limit.max_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getMaxLimit() {
		return maxLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.max_limit
	 * @param maxLimit  the value for bet_limit.max_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setMaxLimit(String maxLimit) {
		this.maxLimit = maxLimit == null ? null : maxLimit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.min_limit
	 * @return  the value of bet_limit.min_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getMinLimit() {
		return minLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.min_limit
	 * @param minLimit  the value for bet_limit.min_limit
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setMinLimit(String minLimit) {
		this.minLimit = minLimit == null ? null : minLimit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.oddtype
	 * @return  the value of bet_limit.oddtype
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getOddtype() {
		return oddtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.oddtype
	 * @param oddtype  the value for bet_limit.oddtype
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setOddtype(String oddtype) {
		this.oddtype = oddtype == null ? null : oddtype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.currency_type
	 * @return  the value of bet_limit.currency_type
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getCurrencyType() {
		return currencyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.currency_type
	 * @param currencyType  the value for bet_limit.currency_type
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType == null ? null : currencyType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.operator
	 * @return  the value of bet_limit.operator
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.operator
	 * @param operator  the value for bet_limit.operator
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.state
	 * @return  the value of bet_limit.state
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.state
	 * @param state  the value for bet_limit.state
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.create_time
	 * @return  the value of bet_limit.create_time
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.create_time
	 * @param createTime  the value for bet_limit.create_time
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime == null ? null : createTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bet_limit.update_time
	 * @return  the value of bet_limit.update_time
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bet_limit.update_time
	 * @param updateTime  the value for bet_limit.update_time
	 * @mbggenerated  Mon Jun 04 17:32:00 CST 2018
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime == null ? null : updateTime.trim();
	}
}