package com.ds.transfer.record.entity;

public class PtApiUserEntity implements java.io.Serializable{
    /** 
	* @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
	*/ 
	private static final long serialVersionUID = 1474885125292166292L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.username
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.password
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.agent_name
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private String agentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.api_info_id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private Integer apiInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.site_id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.site_name
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private String siteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.oddtype
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private String oddtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.currency_type
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private String currencyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.create_time
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_api_user.user_status
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    private Integer userStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.id
     *
     * @return the value of pt_api_user.id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.id
     *
     * @param id the value for pt_api_user.id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.username
     *
     * @return the value of pt_api_user.username
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.username
     *
     * @param username the value for pt_api_user.username
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.password
     *
     * @return the value of pt_api_user.password
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.password
     *
     * @param password the value for pt_api_user.password
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.agent_name
     *
     * @return the value of pt_api_user.agent_name
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.agent_name
     *
     * @param agentName the value for pt_api_user.agent_name
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName == null ? null : agentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.api_info_id
     *
     * @return the value of pt_api_user.api_info_id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public Integer getApiInfoId() {
        return apiInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.api_info_id
     *
     * @param apiInfoId the value for pt_api_user.api_info_id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setApiInfoId(Integer apiInfoId) {
        this.apiInfoId = apiInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.site_id
     *
     * @return the value of pt_api_user.site_id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.site_id
     *
     * @param siteId the value for pt_api_user.site_id
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.site_name
     *
     * @return the value of pt_api_user.site_name
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.site_name
     *
     * @param siteName the value for pt_api_user.site_name
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.oddtype
     *
     * @return the value of pt_api_user.oddtype
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public String getOddtype() {
        return oddtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.oddtype
     *
     * @param oddtype the value for pt_api_user.oddtype
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setOddtype(String oddtype) {
        this.oddtype = oddtype == null ? null : oddtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.currency_type
     *
     * @return the value of pt_api_user.currency_type
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.currency_type
     *
     * @param currencyType the value for pt_api_user.currency_type
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.create_time
     *
     * @return the value of pt_api_user.create_time
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.create_time
     *
     * @param createTime the value for pt_api_user.create_time
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_api_user.user_status
     *
     * @return the value of pt_api_user.user_status
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_api_user.user_status
     *
     * @param userStatus the value for pt_api_user.user_status
     *
     * @mbggenerated Mon Oct 23 11:44:00 CST 2017
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }
}