package com.ds.transfer.record.entity;

public class TransferOtherRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.site_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.username
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.transfer_money
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private String transferMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.trans_center_billno
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private String transCenterBillno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.trans_mapping_billno
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private String transMappingBillno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.trans_type
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private String transType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.live_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private Integer liveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.live_type
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private String liveType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.trans_record_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private Long transRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.create_time
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_other_rule.update_time
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.id
     *
     * @return the value of transfer_other_rule.id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.id
     *
     * @param id the value for transfer_other_rule.id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.site_id
     *
     * @return the value of transfer_other_rule.site_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.site_id
     *
     * @param siteId the value for transfer_other_rule.site_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.username
     *
     * @return the value of transfer_other_rule.username
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.username
     *
     * @param username the value for transfer_other_rule.username
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.transfer_money
     *
     * @return the value of transfer_other_rule.transfer_money
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public String getTransferMoney() {
        return transferMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.transfer_money
     *
     * @param transferMoney the value for transfer_other_rule.transfer_money
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setTransferMoney(String transferMoney) {
        this.transferMoney = transferMoney == null ? null : transferMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.trans_center_billno
     *
     * @return the value of transfer_other_rule.trans_center_billno
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public String getTransCenterBillno() {
        return transCenterBillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.trans_center_billno
     *
     * @param transCenterBillno the value for transfer_other_rule.trans_center_billno
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setTransCenterBillno(String transCenterBillno) {
        this.transCenterBillno = transCenterBillno == null ? null : transCenterBillno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.trans_mapping_billno
     *
     * @return the value of transfer_other_rule.trans_mapping_billno
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public String getTransMappingBillno() {
        return transMappingBillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.trans_mapping_billno
     *
     * @param transMappingBillno the value for transfer_other_rule.trans_mapping_billno
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setTransMappingBillno(String transMappingBillno) {
        this.transMappingBillno = transMappingBillno == null ? null : transMappingBillno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.trans_type
     *
     * @return the value of transfer_other_rule.trans_type
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.trans_type
     *
     * @param transType the value for transfer_other_rule.trans_type
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setTransType(String transType) {
        this.transType = transType == null ? null : transType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.live_id
     *
     * @return the value of transfer_other_rule.live_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public Integer getLiveId() {
        return liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.live_id
     *
     * @param liveId the value for transfer_other_rule.live_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setLiveId(Integer liveId) {
        this.liveId = liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.live_type
     *
     * @return the value of transfer_other_rule.live_type
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public String getLiveType() {
        return liveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.live_type
     *
     * @param liveType the value for transfer_other_rule.live_type
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setLiveType(String liveType) {
        this.liveType = liveType == null ? null : liveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.trans_record_id
     *
     * @return the value of transfer_other_rule.trans_record_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public Long getTransRecordId() {
        return transRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.trans_record_id
     *
     * @param transRecordId the value for transfer_other_rule.trans_record_id
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setTransRecordId(Long transRecordId) {
        this.transRecordId = transRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.create_time
     *
     * @return the value of transfer_other_rule.create_time
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.create_time
     *
     * @param createTime the value for transfer_other_rule.create_time
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_other_rule.update_time
     *
     * @return the value of transfer_other_rule.update_time
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_other_rule.update_time
     *
     * @param updateTime the value for transfer_other_rule.update_time
     *
     * @mbggenerated Thu May 10 16:02:09 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}