package com.ds.transfer.record.entity;

import java.io.Serializable;

public class TransferRecordEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.username
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.password
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.transfer_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String transferMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.trans_billno
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String transBillno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.trans_status
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private Integer transStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.trans_type
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String transType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.trans_before_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private Double transBeforeMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.trans_after_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private Double transAfterMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.live_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private Integer liveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.live_type
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String liveType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.trans_record_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private Long transRecordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.finger
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String finger;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.remark
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.create_time
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.update_time
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private String updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.versions
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private Integer versions;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_record.site_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	private Integer siteId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.id
	 * @return  the value of transfer_record.id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.id
	 * @param id  the value for transfer_record.id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.username
	 * @return  the value of transfer_record.username
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.username
	 * @param username  the value for transfer_record.username
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.password
	 * @return  the value of transfer_record.password
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.password
	 * @param password  the value for transfer_record.password
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.transfer_money
	 * @return  the value of transfer_record.transfer_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getTransferMoney() {
		return transferMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.transfer_money
	 * @param transferMoney  the value for transfer_record.transfer_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setTransferMoney(String transferMoney) {
		this.transferMoney = transferMoney == null ? null : transferMoney.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.trans_billno
	 * @return  the value of transfer_record.trans_billno
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getTransBillno() {
		return transBillno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.trans_billno
	 * @param transBillno  the value for transfer_record.trans_billno
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setTransBillno(String transBillno) {
		this.transBillno = transBillno == null ? null : transBillno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.trans_status
	 * @return  the value of transfer_record.trans_status
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Integer getTransStatus() {
		return transStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.trans_status
	 * @param transStatus  the value for transfer_record.trans_status
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setTransStatus(Integer transStatus) {
		this.transStatus = transStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.trans_type
	 * @return  the value of transfer_record.trans_type
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getTransType() {
		return transType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.trans_type
	 * @param transType  the value for transfer_record.trans_type
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setTransType(String transType) {
		this.transType = transType == null ? null : transType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.trans_before_money
	 * @return  the value of transfer_record.trans_before_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Double getTransBeforeMoney() {
		return transBeforeMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.trans_before_money
	 * @param transBeforeMoney  the value for transfer_record.trans_before_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setTransBeforeMoney(Double transBeforeMoney) {
		this.transBeforeMoney = transBeforeMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.trans_after_money
	 * @return  the value of transfer_record.trans_after_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Double getTransAfterMoney() {
		return transAfterMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.trans_after_money
	 * @param transAfterMoney  the value for transfer_record.trans_after_money
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setTransAfterMoney(Double transAfterMoney) {
		this.transAfterMoney = transAfterMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.live_id
	 * @return  the value of transfer_record.live_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Integer getLiveId() {
		return liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.live_id
	 * @param liveId  the value for transfer_record.live_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setLiveId(Integer liveId) {
		this.liveId = liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.live_type
	 * @return  the value of transfer_record.live_type
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getLiveType() {
		return liveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.live_type
	 * @param liveType  the value for transfer_record.live_type
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setLiveType(String liveType) {
		this.liveType = liveType == null ? null : liveType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.trans_record_id
	 * @return  the value of transfer_record.trans_record_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Long getTransRecordId() {
		return transRecordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.trans_record_id
	 * @param transRecordId  the value for transfer_record.trans_record_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setTransRecordId(Long transRecordId) {
		this.transRecordId = transRecordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.finger
	 * @return  the value of transfer_record.finger
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getFinger() {
		return finger;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.finger
	 * @param finger  the value for transfer_record.finger
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setFinger(String finger) {
		this.finger = finger == null ? null : finger.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.remark
	 * @return  the value of transfer_record.remark
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.remark
	 * @param remark  the value for transfer_record.remark
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.create_time
	 * @return  the value of transfer_record.create_time
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.create_time
	 * @param createTime  the value for transfer_record.create_time
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime == null ? null : createTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.update_time
	 * @return  the value of transfer_record.update_time
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.update_time
	 * @param updateTime  the value for transfer_record.update_time
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime == null ? null : updateTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.versions
	 * @return  the value of transfer_record.versions
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Integer getVersions() {
		return versions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.versions
	 * @param versions  the value for transfer_record.versions
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setVersions(Integer versions) {
		this.versions = versions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_record.site_id
	 * @return  the value of transfer_record.site_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_record.site_id
	 * @param siteId  the value for transfer_record.site_id
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	private static final long serialVersionUID = 8448732820106998803L;

	@Override
	public String toString() {
		return "TransferRecordEntity [id=" + id + ", username=" + username
				+ ", password=" + password + ", transferMoney=" + transferMoney
				+ ", transBillno=" + transBillno + ", transStatus="
				+ transStatus + ", transType=" + transType
				+ ", transBeforeMoney=" + transBeforeMoney
				+ ", transAfterMoney=" + transAfterMoney + ", liveId=" + liveId
				+ ", liveType=" + liveType + ", transRecordId=" + transRecordId
				+ ", finger=" + finger + ", remark=" + remark + ", createTime="
				+ createTime + ", updateTime=" + updateTime + ", versions="
				+ versions + ", siteId=" + siteId + "]";
	}
}