package com.ds.transfer.record.entity;

import java.util.ArrayList;
import java.util.List;

public class TransferRecordEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public TransferRecordEntityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyIsNull() {
			addCriterion("transfer_money is null");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyIsNotNull() {
			addCriterion("transfer_money is not null");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyEqualTo(String value) {
			addCriterion("transfer_money =", value, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyNotEqualTo(String value) {
			addCriterion("transfer_money <>", value, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyGreaterThan(String value) {
			addCriterion("transfer_money >", value, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyGreaterThanOrEqualTo(String value) {
			addCriterion("transfer_money >=", value, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyLessThan(String value) {
			addCriterion("transfer_money <", value, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyLessThanOrEqualTo(String value) {
			addCriterion("transfer_money <=", value, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyLike(String value) {
			addCriterion("transfer_money like", value, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyNotLike(String value) {
			addCriterion("transfer_money not like", value, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyIn(List<String> values) {
			addCriterion("transfer_money in", values, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyNotIn(List<String> values) {
			addCriterion("transfer_money not in", values, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyBetween(String value1, String value2) {
			addCriterion("transfer_money between", value1, value2, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransferMoneyNotBetween(String value1, String value2) {
			addCriterion("transfer_money not between", value1, value2, "transferMoney");
			return (Criteria) this;
		}

		public Criteria andTransBillnoIsNull() {
			addCriterion("trans_billno is null");
			return (Criteria) this;
		}

		public Criteria andTransBillnoIsNotNull() {
			addCriterion("trans_billno is not null");
			return (Criteria) this;
		}

		public Criteria andTransBillnoEqualTo(String value) {
			addCriterion("trans_billno =", value, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoNotEqualTo(String value) {
			addCriterion("trans_billno <>", value, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoGreaterThan(String value) {
			addCriterion("trans_billno >", value, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoGreaterThanOrEqualTo(String value) {
			addCriterion("trans_billno >=", value, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoLessThan(String value) {
			addCriterion("trans_billno <", value, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoLessThanOrEqualTo(String value) {
			addCriterion("trans_billno <=", value, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoLike(String value) {
			addCriterion("trans_billno like", value, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoNotLike(String value) {
			addCriterion("trans_billno not like", value, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoIn(List<String> values) {
			addCriterion("trans_billno in", values, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoNotIn(List<String> values) {
			addCriterion("trans_billno not in", values, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoBetween(String value1, String value2) {
			addCriterion("trans_billno between", value1, value2, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransBillnoNotBetween(String value1, String value2) {
			addCriterion("trans_billno not between", value1, value2, "transBillno");
			return (Criteria) this;
		}

		public Criteria andTransStatusIsNull() {
			addCriterion("trans_status is null");
			return (Criteria) this;
		}

		public Criteria andTransStatusIsNotNull() {
			addCriterion("trans_status is not null");
			return (Criteria) this;
		}

		public Criteria andTransStatusEqualTo(Integer value) {
			addCriterion("trans_status =", value, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusNotEqualTo(Integer value) {
			addCriterion("trans_status <>", value, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusGreaterThan(Integer value) {
			addCriterion("trans_status >", value, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("trans_status >=", value, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusLessThan(Integer value) {
			addCriterion("trans_status <", value, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusLessThanOrEqualTo(Integer value) {
			addCriterion("trans_status <=", value, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusIn(List<Integer> values) {
			addCriterion("trans_status in", values, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusNotIn(List<Integer> values) {
			addCriterion("trans_status not in", values, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusBetween(Integer value1, Integer value2) {
			addCriterion("trans_status between", value1, value2, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("trans_status not between", value1, value2, "transStatus");
			return (Criteria) this;
		}

		public Criteria andTransTypeIsNull() {
			addCriterion("trans_type is null");
			return (Criteria) this;
		}

		public Criteria andTransTypeIsNotNull() {
			addCriterion("trans_type is not null");
			return (Criteria) this;
		}

		public Criteria andTransTypeEqualTo(String value) {
			addCriterion("trans_type =", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeNotEqualTo(String value) {
			addCriterion("trans_type <>", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeGreaterThan(String value) {
			addCriterion("trans_type >", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeGreaterThanOrEqualTo(String value) {
			addCriterion("trans_type >=", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeLessThan(String value) {
			addCriterion("trans_type <", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeLessThanOrEqualTo(String value) {
			addCriterion("trans_type <=", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeLike(String value) {
			addCriterion("trans_type like", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeNotLike(String value) {
			addCriterion("trans_type not like", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeIn(List<String> values) {
			addCriterion("trans_type in", values, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeNotIn(List<String> values) {
			addCriterion("trans_type not in", values, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeBetween(String value1, String value2) {
			addCriterion("trans_type between", value1, value2, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeNotBetween(String value1, String value2) {
			addCriterion("trans_type not between", value1, value2, "transType");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyIsNull() {
			addCriterion("trans_before_money is null");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyIsNotNull() {
			addCriterion("trans_before_money is not null");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyEqualTo(Double value) {
			addCriterion("trans_before_money =", value, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyNotEqualTo(Double value) {
			addCriterion("trans_before_money <>", value, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyGreaterThan(Double value) {
			addCriterion("trans_before_money >", value, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("trans_before_money >=", value, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyLessThan(Double value) {
			addCriterion("trans_before_money <", value, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyLessThanOrEqualTo(Double value) {
			addCriterion("trans_before_money <=", value, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyIn(List<Double> values) {
			addCriterion("trans_before_money in", values, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyNotIn(List<Double> values) {
			addCriterion("trans_before_money not in", values, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyBetween(Double value1, Double value2) {
			addCriterion("trans_before_money between", value1, value2, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransBeforeMoneyNotBetween(Double value1, Double value2) {
			addCriterion("trans_before_money not between", value1, value2, "transBeforeMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyIsNull() {
			addCriterion("trans_after_money is null");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyIsNotNull() {
			addCriterion("trans_after_money is not null");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyEqualTo(Double value) {
			addCriterion("trans_after_money =", value, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyNotEqualTo(Double value) {
			addCriterion("trans_after_money <>", value, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyGreaterThan(Double value) {
			addCriterion("trans_after_money >", value, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("trans_after_money >=", value, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyLessThan(Double value) {
			addCriterion("trans_after_money <", value, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyLessThanOrEqualTo(Double value) {
			addCriterion("trans_after_money <=", value, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyIn(List<Double> values) {
			addCriterion("trans_after_money in", values, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyNotIn(List<Double> values) {
			addCriterion("trans_after_money not in", values, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyBetween(Double value1, Double value2) {
			addCriterion("trans_after_money between", value1, value2, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andTransAfterMoneyNotBetween(Double value1, Double value2) {
			addCriterion("trans_after_money not between", value1, value2, "transAfterMoney");
			return (Criteria) this;
		}

		public Criteria andLiveIdIsNull() {
			addCriterion("live_id is null");
			return (Criteria) this;
		}

		public Criteria andLiveIdIsNotNull() {
			addCriterion("live_id is not null");
			return (Criteria) this;
		}

		public Criteria andLiveIdEqualTo(Integer value) {
			addCriterion("live_id =", value, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdNotEqualTo(Integer value) {
			addCriterion("live_id <>", value, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdGreaterThan(Integer value) {
			addCriterion("live_id >", value, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("live_id >=", value, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdLessThan(Integer value) {
			addCriterion("live_id <", value, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdLessThanOrEqualTo(Integer value) {
			addCriterion("live_id <=", value, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdIn(List<Integer> values) {
			addCriterion("live_id in", values, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdNotIn(List<Integer> values) {
			addCriterion("live_id not in", values, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdBetween(Integer value1, Integer value2) {
			addCriterion("live_id between", value1, value2, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveIdNotBetween(Integer value1, Integer value2) {
			addCriterion("live_id not between", value1, value2, "liveId");
			return (Criteria) this;
		}

		public Criteria andLiveTypeIsNull() {
			addCriterion("live_type is null");
			return (Criteria) this;
		}

		public Criteria andLiveTypeIsNotNull() {
			addCriterion("live_type is not null");
			return (Criteria) this;
		}

		public Criteria andLiveTypeEqualTo(String value) {
			addCriterion("live_type =", value, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeNotEqualTo(String value) {
			addCriterion("live_type <>", value, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeGreaterThan(String value) {
			addCriterion("live_type >", value, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeGreaterThanOrEqualTo(String value) {
			addCriterion("live_type >=", value, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeLessThan(String value) {
			addCriterion("live_type <", value, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeLessThanOrEqualTo(String value) {
			addCriterion("live_type <=", value, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeLike(String value) {
			addCriterion("live_type like", value, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeNotLike(String value) {
			addCriterion("live_type not like", value, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeIn(List<String> values) {
			addCriterion("live_type in", values, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeNotIn(List<String> values) {
			addCriterion("live_type not in", values, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeBetween(String value1, String value2) {
			addCriterion("live_type between", value1, value2, "liveType");
			return (Criteria) this;
		}

		public Criteria andLiveTypeNotBetween(String value1, String value2) {
			addCriterion("live_type not between", value1, value2, "liveType");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdIsNull() {
			addCriterion("trans_record_id is null");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdIsNotNull() {
			addCriterion("trans_record_id is not null");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdEqualTo(Long value) {
			addCriterion("trans_record_id =", value, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdNotEqualTo(Long value) {
			addCriterion("trans_record_id <>", value, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdGreaterThan(Long value) {
			addCriterion("trans_record_id >", value, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdGreaterThanOrEqualTo(Long value) {
			addCriterion("trans_record_id >=", value, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdLessThan(Long value) {
			addCriterion("trans_record_id <", value, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdLessThanOrEqualTo(Long value) {
			addCriterion("trans_record_id <=", value, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdIn(List<Long> values) {
			addCriterion("trans_record_id in", values, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdNotIn(List<Long> values) {
			addCriterion("trans_record_id not in", values, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdBetween(Long value1, Long value2) {
			addCriterion("trans_record_id between", value1, value2, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andTransRecordIdNotBetween(Long value1, Long value2) {
			addCriterion("trans_record_id not between", value1, value2, "transRecordId");
			return (Criteria) this;
		}

		public Criteria andFingerIsNull() {
			addCriterion("finger is null");
			return (Criteria) this;
		}

		public Criteria andFingerIsNotNull() {
			addCriterion("finger is not null");
			return (Criteria) this;
		}

		public Criteria andFingerEqualTo(String value) {
			addCriterion("finger =", value, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerNotEqualTo(String value) {
			addCriterion("finger <>", value, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerGreaterThan(String value) {
			addCriterion("finger >", value, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerGreaterThanOrEqualTo(String value) {
			addCriterion("finger >=", value, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerLessThan(String value) {
			addCriterion("finger <", value, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerLessThanOrEqualTo(String value) {
			addCriterion("finger <=", value, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerLike(String value) {
			addCriterion("finger like", value, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerNotLike(String value) {
			addCriterion("finger not like", value, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerIn(List<String> values) {
			addCriterion("finger in", values, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerNotIn(List<String> values) {
			addCriterion("finger not in", values, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerBetween(String value1, String value2) {
			addCriterion("finger between", value1, value2, "finger");
			return (Criteria) this;
		}

		public Criteria andFingerNotBetween(String value1, String value2) {
			addCriterion("finger not between", value1, value2, "finger");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("create_time like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("create_time not like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(String value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(String value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(String value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(String value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLike(String value) {
			addCriterion("update_time like", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotLike(String value) {
			addCriterion("update_time not like", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<String> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<String> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(String value1, String value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(String value1, String value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andVersionsIsNull() {
			addCriterion("versions is null");
			return (Criteria) this;
		}

		public Criteria andVersionsIsNotNull() {
			addCriterion("versions is not null");
			return (Criteria) this;
		}

		public Criteria andVersionsEqualTo(Integer value) {
			addCriterion("versions =", value, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsNotEqualTo(Integer value) {
			addCriterion("versions <>", value, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsGreaterThan(Integer value) {
			addCriterion("versions >", value, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsGreaterThanOrEqualTo(Integer value) {
			addCriterion("versions >=", value, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsLessThan(Integer value) {
			addCriterion("versions <", value, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsLessThanOrEqualTo(Integer value) {
			addCriterion("versions <=", value, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsIn(List<Integer> values) {
			addCriterion("versions in", values, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsNotIn(List<Integer> values) {
			addCriterion("versions not in", values, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsBetween(Integer value1, Integer value2) {
			addCriterion("versions between", value1, value2, "versions");
			return (Criteria) this;
		}

		public Criteria andVersionsNotBetween(Integer value1, Integer value2) {
			addCriterion("versions not between", value1, value2, "versions");
			return (Criteria) this;
		}

		public Criteria andSiteIdIsNull() {
			addCriterion("site_id is null");
			return (Criteria) this;
		}

		public Criteria andSiteIdIsNotNull() {
			addCriterion("site_id is not null");
			return (Criteria) this;
		}

		public Criteria andSiteIdEqualTo(Integer value) {
			addCriterion("site_id =", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotEqualTo(Integer value) {
			addCriterion("site_id <>", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdGreaterThan(Integer value) {
			addCriterion("site_id >", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("site_id >=", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLessThan(Integer value) {
			addCriterion("site_id <", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLessThanOrEqualTo(Integer value) {
			addCriterion("site_id <=", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdIn(List<Integer> values) {
			addCriterion("site_id in", values, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotIn(List<Integer> values) {
			addCriterion("site_id not in", values, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdBetween(Integer value1, Integer value2) {
			addCriterion("site_id between", value1, value2, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotBetween(Integer value1, Integer value2) {
			addCriterion("site_id not between", value1, value2, "siteId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table transfer_record
	 * @mbggenerated  Tue Dec 29 20:28:58 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transfer_record
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 05 14:47:01 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}