package com.ds.transfer.record.entity;

import java.util.Date;

public class TransferRemarkConfEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_remark_conf.id
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_remark_conf.project
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_remark_conf.remark_field
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    private String remarkField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_remark_conf.content
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_remark_conf.create_time
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_remark_conf.update_time
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_remark_conf.id
     *
     * @return the value of transfer_remark_conf.id
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_remark_conf.id
     *
     * @param id the value for transfer_remark_conf.id
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_remark_conf.project
     *
     * @return the value of transfer_remark_conf.project
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_remark_conf.project
     *
     * @param project the value for transfer_remark_conf.project
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_remark_conf.remark_field
     *
     * @return the value of transfer_remark_conf.remark_field
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public String getRemarkField() {
        return remarkField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_remark_conf.remark_field
     *
     * @param remarkField the value for transfer_remark_conf.remark_field
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public void setRemarkField(String remarkField) {
        this.remarkField = remarkField == null ? null : remarkField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_remark_conf.content
     *
     * @return the value of transfer_remark_conf.content
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_remark_conf.content
     *
     * @param content the value for transfer_remark_conf.content
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_remark_conf.create_time
     *
     * @return the value of transfer_remark_conf.create_time
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_remark_conf.create_time
     *
     * @param createTime the value for transfer_remark_conf.create_time
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_remark_conf.update_time
     *
     * @return the value of transfer_remark_conf.update_time
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_remark_conf.update_time
     *
     * @param updateTime the value for transfer_remark_conf.update_time
     *
     * @mbggenerated Sat Aug 04 11:34:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}