package com.ds.transfer.money.mapper;

import com.ds.transfer.money.entity.TransferMoneyKeyEntity;
import com.ds.transfer.money.entity.TransferMoneyKeyEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferMoneyKeyEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int countByExample(TransferMoneyKeyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int deleteByExample(TransferMoneyKeyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int insert(TransferMoneyKeyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int insertSelective(TransferMoneyKeyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    List<TransferMoneyKeyEntity> selectByExample(TransferMoneyKeyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    TransferMoneyKeyEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") TransferMoneyKeyEntity record, @Param("example") TransferMoneyKeyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int updateByExample(@Param("record") TransferMoneyKeyEntity record, @Param("example") TransferMoneyKeyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int updateByPrimaryKeySelective(TransferMoneyKeyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_money_key
     *
     * @mbggenerated Tue Nov 24 20:39:37 CST 2015
     */
    int updateByPrimaryKey(TransferMoneyKeyEntity record);
}