package com.ds.transfer.http.entity;

import java.util.Date;

public class PlatformUrl {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column platform_url.id
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column platform_url.platform_id
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	private Integer platformId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column platform_url.platform_type
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	private String platformType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column platform_url.platform_url
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	private String platformUrl;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column platform_url.status
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column platform_url.memo
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	private String memo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column platform_url.create_time
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column platform_url.update_time
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column platform_url.id
	 *
	 * @return the value of platform_url.id
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column platform_url.id
	 *
	 * @param id the value for platform_url.id
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column platform_url.platform_id
	 *
	 * @return the value of platform_url.platform_id
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public Integer getPlatformId() {
		return platformId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column platform_url.platform_id
	 *
	 * @param platformId the value for platform_url.platform_id
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column platform_url.platform_type
	 *
	 * @return the value of platform_url.platform_type
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public String getPlatformType() {
		return platformType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column platform_url.platform_type
	 *
	 * @param platformType the value for platform_url.platform_type
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public void setPlatformType(String platformType) {
		this.platformType = platformType == null ? null : platformType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column platform_url.platform_url
	 *
	 * @return the value of platform_url.platform_url
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public String getPlatformUrl() {
		return platformUrl;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column platform_url.platform_url
	 *
	 * @param platformUrl the value for platform_url.platform_url
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public void setPlatformUrl(String platformUrl) {
		this.platformUrl = platformUrl == null ? null : platformUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column platform_url.status
	 *
	 * @return the value of platform_url.status
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column platform_url.status
	 *
	 * @param status the value for platform_url.status
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column platform_url.memo
	 *
	 * @return the value of platform_url.memo
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column platform_url.memo
	 *
	 * @param memo the value for platform_url.memo
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column platform_url.create_time
	 *
	 * @return the value of platform_url.create_time
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column platform_url.create_time
	 *
	 * @param createTime the value for platform_url.create_time
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column platform_url.update_time
	 *
	 * @return the value of platform_url.update_time
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column platform_url.update_time
	 *
	 * @param updateTime the value for platform_url.update_time
	 *
	 * @mbggenerated Mon Sep 19 15:02:09 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}